baseURL = "http://example.org/"
title = "Cvit travel agency"
defaultContentLanguage = "hr"


[languages.en]
    weight = 0
    languageName = "flagen"
    LanguageCode = "en"

[languages.hr]
    weight = 10
    languageName = "flagcro"
    LanguageCode = "hr"

[languages.swe]
    weight = 20
    languageName = "flagswe"
    LanguageCode = "swe"